server:
  port: 9026
spring:
  application:
    name: tensquare-split
  data:
    mongodb:
      host: 192.168.25.130
      database: splitdb
  redis:
    host: 192.168.25.130
eureka:
  client:
    service-url:
      defauleZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true